"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Shape_1 = require("./Shape");
var Circle_1 = require("./Circle");
var Rectangle_1 = require("./Rectangle");
var s = new Shape_1.Shape(10, 20);
console.log(s.getInfo());
var c = new Circle_1.Circle(10, 20, 30);
console.log(c.getInfo());
var r = new Rectangle_1.Rectanle(0, 0, 3, 7);
console.log(r.getInfo());
